#!/usr/bin/env python3
"""workflow_export.py — Export workflow JSON + auto-generate README.md companion.

Reads workflow JSON, extract metadata, generate README.md with Mermaid diagram,
node-by-node explanation, setup checklist, test instructions, monitoring section.

Usage: python3 workflow_export.py <workflow.json> --output README.md [--language italian|english]
"""

import argparse
import json
import sys
from pathlib import Path
from datetime import datetime


def generate_mermaid(workflow: dict) -> str:
    nodes = workflow.get("nodes", [])
    connections = workflow.get("connections", {})

    def node_class(node):
        ntype = node.get("type", "")
        if any(
            k in ntype
            for k in ["webhook", "scheduleTrigger", "chatTrigger", "manualTrigger"]
        ):
            return "trigger"
        if "respondToWebhook" in ntype:
            return "output"
        return "action"

    sanitize = lambda s: (
        s.replace(" ", "_").replace("(", "").replace(")", "").replace("/", "_")
    )

    lines = ["```mermaid", "graph TD"]
    for node in nodes:
        nid = sanitize(node["name"])
        label = f"{node['name']}<br/>{node.get('type', '').split('.')[-1]}"
        lines.append(f"    {nid}[{label}]")

    for source, conn in connections.items():
        for output_type, branches in conn.items():
            for branch in branches:
                for target in branch:
                    src = sanitize(source)
                    tgt = sanitize(target.get("node", ""))
                    if tgt:
                        lines.append(f"    {src} --> {tgt}")

    lines.append("    classDef trigger fill:#90EE90")
    lines.append("    classDef action fill:#87CEEB")
    lines.append("    classDef output fill:#FFB347")

    triggers = [sanitize(n["name"]) for n in nodes if node_class(n) == "trigger"]
    outputs = [sanitize(n["name"]) for n in nodes if node_class(n) == "output"]
    actions = [sanitize(n["name"]) for n in nodes if node_class(n) == "action"]

    if triggers:
        lines.append(f"    class {','.join(triggers)} trigger")
    if actions:
        lines.append(f"    class {','.join(actions)} action")
    if outputs:
        lines.append(f"    class {','.join(outputs)} output")

    lines.append("```")
    return "\n".join(lines)


def extract_credentials(workflow: dict) -> list:
    creds = []
    for node in workflow.get("nodes", []):
        if "credentials" in node:
            for cred_type, cred_data in node["credentials"].items():
                creds.append(
                    {
                        "type": cred_type,
                        "name": cred_data.get("name", "REPLACE_ME"),
                        "node": node["name"],
                    }
                )
    return creds


def extract_env_vars(workflow: dict) -> list:
    import re

    workflow_str = json.dumps(workflow)
    pattern = re.compile(r"\$env\.([A-Z_][A-Z0-9_]*)")
    return sorted(set(pattern.findall(workflow_str)))


def has_ai_agent(workflow: dict) -> bool:
    return any(
        n.get("type", "") == "@n8n/n8n-nodes-langchain.agent"
        for n in workflow.get("nodes", [])
    )


def generate_readme(workflow: dict, language: str = "italian") -> str:
    name = workflow.get("name", "Workflow")
    nodes = workflow.get("nodes", [])
    creds = extract_credentials(workflow)
    env_vars = extract_env_vars(workflow)
    has_ai = has_ai_agent(workflow)

    today = datetime.now().strftime("%Y-%m-%d")

    is_it = language == "italian"

    sections = []
    sections.append(f"# {name}\n")
    sections.append(f"> Auto-generated by /automation-architect on {today}\n")

    sections.append("## Purpose\n")
    sections.append("<!-- TODO: 1-2 sentences cosa fa il workflow -->\n")

    sections.append("## Architecture\n")
    sections.append(generate_mermaid(workflow) + "\n")

    sections.append("## Trigger & Flow\n")
    for i, node in enumerate(nodes, 1):
        sections.append(f"### {i}. {node['name']}\n")
        sections.append(f"- **Type**: `{node.get('type', 'unknown')}`")
        sections.append(f"- **Purpose**: <!-- TODO: brief explanation -->\n")

    sections.append("## Setup\n")

    if creds:
        sections.append(
            "### Credentials da creare in n8n\n"
            if is_it
            else "### Credentials to create in n8n\n"
        )
        for c in creds:
            sections.append(f"- [ ] **{c['type']}** (used in: `{c['node']}`)")
        sections.append("")

    if env_vars:
        sections.append("### Environment Variables\n")
        for v in env_vars:
            sections.append(f"- [ ] `{v}`: <!-- describe -->")
        sections.append("")

    sections.append("### N8n config\n")
    sections.append("- [ ] Activate workflow")
    sections.append("- [ ] Assign Error Workflow (Settings → Error Workflow)")
    sections.append("")

    sections.append("## Test\n")
    sections.append("Sample payload:\n")
    sections.append("```bash")
    sections.append("# TODO: insert curl example")
    sections.append("```\n")

    sections.append("## Monitoring\n")
    sections.append("- N8n Insights: `<N8N_URL>/workflow/<WF_ID>/executions`")
    sections.append("- Error Workflow alerts to: <!-- Slack channel / email -->\n")

    if has_ai:
        sections.append("## Cost Estimate\n")
        sections.append(
            "- AI Agent uses LLM model — see `model` field in Anthropic Chat Model node"
        )
        sections.append(
            "- Estimate: ~$0.01-0.02 per execution (sonnet, 2k input + 500 output tokens)"
        )
        sections.append("- @ 1k exec/day: ~$15-20/day, ~$450-600/month\n")

    sections.append("## Anti-pattern check\n")
    sections.append("- [ ] Error handling: per-node retry + Error Workflow assigned")
    sections.append("- [ ] No hardcoded secrets (use n8n credentials or env vars)")
    sections.append("- [ ] Webhook HMAC verify (if applicable)")
    sections.append("- [ ] Data minimization (GDPR mode)")
    sections.append("- [ ] HTTP Request timeout esplicito (5000ms)")
    sections.append("- [ ] Max iterations su AI Agent (10 default)")
    sections.append("")

    sections.append("## Changelog\n")
    sections.append(f"- {today}: created via /automation-architect")
    sections.append("")

    return "\n".join(sections)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("workflow_file")
    parser.add_argument("--output", default="-", help="Output file or - for stdout")
    parser.add_argument("--language", default="italian", choices=["italian", "english"])
    args = parser.parse_args()

    workflow = json.loads(Path(args.workflow_file).read_text())
    readme = generate_readme(workflow, args.language)

    if args.output == "-":
        print(readme)
    else:
        Path(args.output).write_text(readme)
        print(f"✓ README written to {args.output}", file=sys.stderr)


if __name__ == "__main__":
    main()
